### PR TITLE
aragorn/robokop

### PR DESCRIPTION
**Pull request by cbizon**
@YaphetKG does this look basically right to you?   I haven't implemented the guts of how robokop is different yet, but I think it exposes the openapi specs correctly.

I think if we decide that we need independent instances, it should be relatively straightforward to just run two of these and play with the ingresses?

### CODE REVIEW

**Comment by YaphetKG** [comment]
Hi @cbizon , The setup looks good, but on the openapi paths generated  for the apps (aragorn  and robokop) saw that they were both being prefixed with the root server location , thus it causes 404 when using the UI. I have made a PR to this branch that'd resolve that (https://github.com/ranking-agent/aragorn/pull/91)

**Comment by cbizon** [comment]
Hi @YaphetKG this version is working locally for me.  It creates both aragorn and robokop endpoints in an instance, each with its own apidocs and smartapi spec.  Both robokop and aragorn endpoints can now handle creative mode queries.  ARAGORN does creative by creating a bunch of calls to strider and merging the results.
ROBOKOP does creative by hitting a pre-built redis database. 
Of course this PR doesn't handle the configurations; I still need to work on the helm charts.

**Comment by cbizon** [comment]
In retrospect, I think that the redis here is a bad idea.  There's not a big gain to be had by caching these results.  Running against robokopkg usually takes < 1 minute even for ~130 rules.    But there are a lot of possible disease/phenotypes, so in aggregate generating the cache takes days.  I think I will modify this code today to leave out the cache and just hit robokopkg directly as the redis-generation is doing.  Then that simplifies everything, including deployment.

**Comment by cbizon** [comment]
OK, redis is backed out.

**Pull request merged**
